ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: ${certificate_issuer_name}
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  hosts:
    - ${grafana_ingress_host}
  tls:
  - hosts:
    - ${grafana_ingress_host}
    secretName: grafana-tls-secret

persistence:
  enabled: true
  size: ${grafana_volume_size}

datasources:
  datasource.yaml:
    apiVersion: 1
    datasources:
      - name: Thanos Querier
        type: prometheus
        access: proxy
        url: thanos-query-frontend:9090
        jsonData:
          mangeAlerts: false
          prometheusType: Thanos
          prometheusVersion: '0.32.1'
      
grafana.ini:
  server:
    root_url: "https://%(domain)s"

  users:
    default_theme: light
    allow_sign_up: false

%{~ if github_org_name != "" ~}
  auth.github:
    enabled: true
    allow_sign_up: true
    auto_login: true
    allowed_organizations: ${github_org_name}
    role_attribute_path: contains(groups[*], '@${github_org_name}/grafana-admins') && 'Admin' || 'Viewer'
    client_secret: ${github_oauth_client_secret}
    client_id: ${github_oauth_client_id}
%{~ endif ~}

